name: Dockerizing with Github Actions

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Login to Dockerhub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push the image
      uses: docker/build-push-action@v2
      with:
          context: .
          push: true
          tags: pmdikshita/start-with-dockerize-manually-and-github-actions:latest
    - name: Start Docker Compose file
      uses: actions/checkout@v3
      with:
        compose-file: "./docker-compose.yaml"
        services: my_service
